### ISSUE TITLE
Unsure if X is supposed to be the Ten?

### ISSUE THREAD

**Issue by Jack-Chronicle** [mAAdhaTTah/obsidian-poker#15]
I'm not getting any Ten cards to render, they could just be replaced by the X or T cards, but I'm not sure if that's intended or a bug

**Comment by mAAdhaTTah** [comment]
Yeah, e.g. `Tc` would be "ten of clubs". You can also do `Xc` to mean "any card of clubs" or `Tx` to mean "ten of any suit". All cards are intended to be represented as 2 characters. I can expand the docs to make this clearer.

**Comment by mAAdhaTTah** [comment]
Let me know if this is clearer: https://github.com/mAAdhaTTah/obsidian-poker/pull/16
