### ISSUE TITLE
I hope the speed will be improved in the future.

### ISSUE THREAD

**Issue by OPEN1004MIND** [mAAdhaTTah/obsidian-poker#17]
It's a very pretty plugin.
However, when I ran it, the speed was too slow while typing in editor mode (&reading view). 
The reason for the slowness seems to be due to its use with background plugins.

I hope the speed will be improved in the future.

**Comment by mAAdhaTTah** [comment]
Can you elaborate? I haven't run into this issue myself. Do you know what "background plugins" might be causing the issue?

**Comment by OPEN1004MIND** [comment]
> Can you elaborate? I haven't run into this issue myself. Do you know what "background plugins" might be causing the issue?

https://github.com/samuelsong70/obsidian-dynamic-background
I am using this plugin. 
However, it is very slow when used together.

**Comment by mAAdhaTTah** [comment]
I just released 1.2.3, which should improve the performance of the editor as the number of usages of the card icons goes up. If you continue to experience performance issues, please provide a Vault with the relevant plugins causing issues, any necessary files that would produce issues, and reproduction steps for it.
